development: &default
  adapter: postgresql
  database: example_development
  port: 5433
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  user: help
  password: help3

test:
  <<: *default
  database: example_test
